services:
  fhir-server:
    # En desarrollo, montamos el pom y src para facilitar pruebas
    # Aunque Java requiere compilación, esto ayuda a ver cambios si usas herramientas de hot-reload
    volumes:
      - .:/app
    # Podrías cambiar el comando para que use jetty:run en lugar de Tomcat si prefieres
    # pero para mantener consistencia con Dockerfile dejamos el default.
    # La memoria (MEM_LIMIT / JAVA_OPTS) se configura en .env
    environment:
      - SHOW_UI=true
